[project]
name = "eggi"
version = "0.0.0"
description = "test"
dependencies = [
    "Flask >= 3.0.0",
    "Flask-SQLAlchemy >= 3.1.1"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"